#############################################################################
# Makefile for building: TankGame
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  TankGame.pro
# Template: app
# Command: /Users/edina/Qt/5.8/clang_64/bin/qmake -o Makefile TankGame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DMAC_OS_X_VERSION_MIN_REQUIRED=1060 -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -std=c99 -I/usr/local/include/SDL2 -D_THREAD_SAFE -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/local/include/SDL2 -I/Users/edina/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Users/edina/Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/edina/Qt/5.8/clang_64/lib
QMAKE         = /Users/edina/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TankGame1.0.0
DISTDIR = /Users/edina/Documents/Programming/TankGame/.tmp/TankGame1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/edina/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/edina/Qt/5.8/clang_64/lib -L/usr/local/lib -lSDL2 -lSDL2_image -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/player.cpp \
		src/ai.cpp \
		src/turningPoint.cpp \
		src/bullet.cpp 
OBJECTS       = main.o \
		player.o \
		ai.o \
		turningPoint.o \
		bullet.o
DIST          = .qmake.stash \
		TankGame.pro include/map.h \
		include/player.h \
		include/gamevalues.h \
		include/ai.h \
		include/turningPoint.h \
		include/bullet.h src/main.cpp \
		src/player.cpp \
		src/ai.cpp \
		src/turningPoint.cpp \
		src/bullet.cpp
QMAKE_TARGET  = TankGame
DESTDIR       = 
TARGET        = TankGame


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TankGame.pro .qmake.cache /Users/edina/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/edina/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/edina/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		TankGame.pro \
		/Users/edina/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile TankGame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/edina/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/qt.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/resources.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/moc.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Users/edina/Qt/5.8/clang_64/mkspecs/features/lex.prf:
TankGame.pro:
/Users/edina/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile TankGame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/edina/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/map.h include/player.h include/gamevalues.h include/ai.h include/turningPoint.h include/bullet.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/player.cpp src/ai.cpp src/turningPoint.cpp src/bullet.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/edina/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Users/edina/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: src/main.cpp /usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		/usr/local/include/SDL2/SDL_image.h \
		include/player.h \
		include/gamevalues.h \
		include/map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

player.o: src/player.cpp include/player.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		include/gamevalues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o src/player.cpp

ai.o: src/ai.cpp include/ai.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		include/gamevalues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ai.o src/ai.cpp

turningPoint.o: src/turningPoint.cpp include/turningPoint.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		include/gamevalues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o turningPoint.o src/turningPoint.cpp

bullet.o: src/bullet.cpp include/bullet.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		include/gamevalues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o src/bullet.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

